language: node_js
node_js:
- "node"
#addons:
#  sonarcloud:
#    organization: "$SONAR_ORGANIZATION"
#    token:
#      secure: "$SONAR_TOKEN"
install:
- npm install
script:
- npm test
#- sonar-scanner
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app:
    develop: vacancy-backend
#notifications:
#  slack: ""
